######################################################################
# Automatically generated by qmake (3.1) Thu Jan 19 12:20:27 2023
######################################################################

QT += testlib
DEFINES += PUNCHCLOCKDE23
CONFIG += debug
TEMPLATE = app
TARGET = test
INCLUDEPATH += . ../src

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += punchclockchecker_test.h ../src/punchclock.h ../src/punchclockchecker.h
SOURCES += punchclockchecker_test.cpp ../src/punchclockchecker.cpp
